# Expose your documentation as JSON swagger compliant
app.swagger:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
  prefix:   /api/doc